# Generated by Django 5.0.3 on 2024-03-26 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='note',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Note'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.CharField(default='e', max_length=1000, verbose_name='Votre critique'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2024)], verbose_name='Date de publication'),
        ),
    ]
